name: ag
version: '2.2.0'
summary: The Silver Searcher
description: A code searching tool similar to ack, with a focus on speed.
base: core22

confinement: strict
grade: stable

apps:
  ag:
    command: usr/local/bin/ag
    plugs:
      - optical-drive
      - process-control
      - removable-media
      - system-backup

parts:
  ag:
    plugin: autotools
    source: https://github.com/ggreer/the_silver_searcher.git
    source-depth: 1
    build-packages:
      - liblzma-dev
      - libpcre3-dev
      - pkg-config
      - zlib1g-dev
