name: ag
version: '2.2.0'
summary: The Silver Searcher
description: A code searching tool similar to ack, with a focus on speed.
base: core22

confinement: devmode
grade: devel

apps:
  ag:
    command: usr/local/bin/ag

parts:
  ag:
    plugin: autotools
    source: https://github.com/ggreer/the_silver_searcher.git
    source-depth: 1
    build-packages:
      - pkg-config
      - libpcre3-dev
      - zlib1g-dev
      - liblzma-dev
